### ISSUE TITLE
Can't obtain depth image, topic /depthimage has no messages

### ISSUE THREAD

**Issue by AIWintermuteAI** [skohlbr/disparity_image_proc#2]
I'm launching the nodelet with following settings.
```
 <node name="disparity_image_proc" pkg="nodelet" type="nodelet" args="load disparity_image_proc/depth_image stereo_proc" output="screen">
    <remap from="/elp/right/camera_info" to="/right/camera_info"/>
    <remap from="/elp/left/camera_info" to="/left/camera_info"/>
    <remap from="/elp/left/image_rect_color" to="/left/image_rect_color"/>
    <remap from="/elp/disparity" to="/disparity"/>
    <remap from="/depth_image" to="/depth_image"/> 
```

The camera works and I can see the information on /camera_info and /image_rect_color topics, as well as disparity image.
Unfortunately the /depth_image topic is empty when I check it with rostopic echo command.
I've tried changing the .cpp file to set Approximate_sync to true, it didn't seem to change anything.
Do you have any ideas on what I might be doing wrong?
Thank you for your help

**Comment by ToniRV** [comment]
Ok I think I got it: just cleaned a bit, removed a redundant image subscriber, change to image_transport, and not much more than that + ofc connecting things appropriately:

![image](https://user-images.githubusercontent.com/9856163/77337783-beb1b900-6cff-11ea-8bc0-e37376bbb25b.png)

**Comment by AIWintermuteAI** [comment]
Okay, I'll close this issue then. I myself also has found a solution that worked for me :) although in the end depth image from stereo cameras wasn't good enough quality, I decided to use Kinect instead
